version: 0.0
os: linux
files:
<<<<<<< HEAD
  - source: /
    destination: /root/Mybackend
=======
  - source: /Mybackend
    destination: /root/mybackend
>>>>>>> 704b7d27098b138b00d744bf9c7957ce4c185537
hooks:
  ApplicationStart:
     - location: scripts/start_server.sh
       timeout: 300
<<<<<<< HEAD
       runas: root
=======
       runas: root
>>>>>>> 704b7d27098b138b00d744bf9c7957ce4c185537
