version: 0.2
env:
  parameter-store:
    MONGO_ENDPOINT: /EKANSH/MONGO_ENDPOINT

phases:
    build:
       commands:
         - npm install
         - sed -i 's/localhost/'$MONGO_ENDPOINT'/' app.js 
artifacts:
  files:
    - '**/*'
